### ISSUE TITLE
Feature Request: Bot timeout

### ISSUE THREAD

**Issue by lonk42** [datahattrick/rustonance#1]
Have bot leave the channel when no audio has been playing for n time or no one is in the channel for n time.

**Comment by datahattrick** [comment]
It seems an issue with the handlers events, what I thought fix one bug as introduced the removal of the idle handle event.

**Comment by datahattrick** [comment]
Well it seems I was incorrect, if was because I had to implement a idle handler... whoops, will be coming through in v0.2.2
