### ISSUE TITLE
Bug: Bot does not auto disconnect when alone and playing audio

### ISSUE THREAD

**Issue by lonk42** [datahattrick/rustonance#7]
While the bot will timeout and disconnect when idle, it won't do so when its playing audio. Its common for users to put hour+ songs on then leave the channels early. The bot will stay alone in the channel finishing the audio.

Instead could the timeout also apply when its alone and playing audio. Stopping the audio and clearing the queue would be acceptable behavior in this scenario.

**Comment by datahattrick** [comment]
Fix will release in 0.4.1
